version: "3"

services:
  database:
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: ops
      POSTGRES_PASSWORD: 123456
